print("nhập 1 chuõi: ")
s = input()

in_hoa = sum(v.isupper for v in s)
print("chữ in HOA: ", in_hoa)
in_thuong = sum(v.islower for v in s)
print("chữ in thường: ", in_thuong)
so = sum(v.isdigit for v in s)
print("chữ số: ", so)
ktdb = sum(not v.isdigit and not v.i for v in s)
print("ký tự đặc biệt: ", ktdb)
ktrong = sum(v.isspace for v in s)
print("khoảng trắng: ", ktrong)
nguyenam =sum(v.lower() in 'aeiou' for v in s)
print("nguyên âm: ", nguyenam)
phu_am = sum(v.isalpha() and v.lower() not in 'aeiou' for v in s)
print("phụ âm: ", phu_am)